"""demo-video recorders.

Storyboards import from here:

    from demo_recording import Recorder          # web apps
    from demo_recording import TerminalRecorder   # CLIs / TUIs
    from demo_recording import stitch             # concat segments -> demo.mp4
"""

from .core import (
    CONTENT_ACTING_VERBS,
    CONTENT_BLANK_FLOOR,
    CONTENT_MOVED_PIXELS,
    CONTENT_PASSIVE_VERBS,
    CONTENT_PIXEL_DELTA,
    CONTENT_SAMPLE_FPS,
    CONTENT_STATIC_WARN_S,
    EVIDENCE_DIR,
    EVIDENCE_LIMITS,
    EVIDENCE_SCHEMA,
    EVIDENCE_TRUNCATED,
    FAILURE_DIR,
    FAILURE_MARKER,
    FAILURE_SCHEMA,
    FRAMES_SCHEMA,
    ISSUE_KINDS,
    MAX_ISSUES,
    OPENING_HOLD_LIMIT_S,
    OPENING_SAMPLE_FPS,
    OPENING_SEARCH_S,
    OPENING_WARN_S,
    SCENE_MIN_SPAN_S,
    SECRET_MASK,
    SECRET_MIN_LEN,
    STRICT_KINDS,
    TIMELINE_SCHEMA,
    Secret,
    SecretLeak,
    StrictTakeFailed,
    beat_frames,
    content_rect,
    content_report,
    evidence_name,
    frames_paths,
    media_duration,
    merge_content,
    opening_gap,
    opening_report,
    opening_warning,
    print_content_summary,
    render_frames_md,
    render_timeline_md,
    scene_times,
    stitch,
    timeline_paths,
    tts_clip,
    write_beat_frames,
    write_timeline,
)
from .terminal import TerminalRecorder
from .web import Recorder

__all__ = [
    "CONTENT_ACTING_VERBS",
    "CONTENT_BLANK_FLOOR",
    "CONTENT_MOVED_PIXELS",
    "CONTENT_PASSIVE_VERBS",
    "CONTENT_PIXEL_DELTA",
    "CONTENT_SAMPLE_FPS",
    "CONTENT_STATIC_WARN_S",
    "EVIDENCE_DIR",
    "EVIDENCE_LIMITS",
    "EVIDENCE_SCHEMA",
    "EVIDENCE_TRUNCATED",
    "FAILURE_DIR",
    "FAILURE_MARKER",
    "FAILURE_SCHEMA",
    "FRAMES_SCHEMA",
    "ISSUE_KINDS",
    "MAX_ISSUES",
    "OPENING_HOLD_LIMIT_S",
    "OPENING_SAMPLE_FPS",
    "OPENING_SEARCH_S",
    "OPENING_WARN_S",
    "Recorder",
    "SCENE_MIN_SPAN_S",
    "SECRET_MASK",
    "SECRET_MIN_LEN",
    "STRICT_KINDS",
    "Secret",
    "SecretLeak",
    "StrictTakeFailed",
    "TIMELINE_SCHEMA",
    "TerminalRecorder",
    "beat_frames",
    "content_report",
    "content_rect",
    "evidence_name",
    "frames_paths",
    "media_duration",
    "merge_content",
    "opening_gap",
    "opening_report",
    "opening_warning",
    "print_content_summary",
    "render_frames_md",
    "render_timeline_md",
    "scene_times",
    "stitch",
    "timeline_paths",
    "tts_clip",
    "write_beat_frames",
    "write_timeline",
]
